sudo: true
dist: trusty

env:
  global:
    - LUAROCKS=2.4.3
  matrix:
    - LUA=lua5.1

language: java

jdk:
  - oraclejdk8

install:
  - who am i
  - sudo snap install luarocks
  - luarocks install luacov
  - luarocks install tapered

before_script:
  - echo 'before'

script:
  - echo 'script'

after_script:
  - echo 'after_script'
